# NumPy arrays and C++ binary IO

cf. Peter Gottschling.  **Discovering Modern C++: An Intensive Course for Scientists, Engineers, and Programmers**, A.2.7 Binary I/O.  

cf. [Writing binary in c++ and read in python](https://stackoverflow.com/questions/37503346/writing-binary-in-c-and-read-in-python)

In [1]:
import numpy
import numpy as np

In [2]:
# find out where we are in the file directory
import os, sys

In [11]:
print(os.getcwd())
datafilefolder = "./data/"

/home/topolo/PropD/CompPhys/Cpp/Cpp14/FileIO


### [`numpy.ndarray.tofile`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.tofile.html)  

`ndarray.tofile(fid,sep="",format="%s")`  

Write array to a file as text or binary (default).  

Data always written in 'C' order, independent of order of *a*.  

#### Parameters  
**fid** : *file or str*  
        An open file object, or string containing filename.  
**sep** : *str*
        Separator between array items for text output.  If "" (empty), a binary file is written, equivalent to `file.write(a.tobytes())`  
**format** : *str*
        Format string for text file output.  Each entry in the array is formatted to text by first converting it to closest Python type, and then using "format" % item.  

In [4]:
m=5
n=4

In [8]:
A = 11.111111*np.array(range(m*n),dtype=np.float32).reshape((m,n))

In [10]:
print(A)

[[   0.           11.11111069   22.22222137   33.33333206]
 [  44.44444275   55.55555344   66.66666412   77.777771  ]
 [  88.8888855   100.          111.11110687  122.22221375]
 [ 133.33332825  144.44444275  155.55554199  166.66665649]
 [ 177.777771    188.8888855   200.          211.11109924]]


In [12]:
A.tofile(datafilefolder+"A_mat_5_4.npy", sep="")

In [17]:
print(os.listdir(datafilefolder))
print(os.listdir(os.getcwd()))

['A_mat_5_4.npy']
['data', '.ipynb_checkpoints', 'FileIO.ipynb', 'binIO_playground.cu']


Then go to CUDA C++14 file `binIO_playground.cu`.  Load it with [`std::ifstream`](http://www.cplusplus.com/reference/fstream/ifstream/), Input stream class to operate on files.  

### `std::ifstream`   
```  
typedef basic_ifstream<char> ifstream;  
```  

### [`reinterpret_cast`](http://en.cppreference.com/w/cpp/language/reinterpret_cast)
